apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinterest-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinterest-clone
  template:
    metadata:
      labels:
        app: pinterest-clone
    spec:
      containers:
      - name: pinterest-clone
        image: karthik792/pinterest-clone  # Docker Hub image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pinterest-service
spec:
  selector:
    app: pinterest-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
