apiVersion: v1
kind: Service
metadata:
  name: pinterest-service
spec:
  type: LoadBalancer
  selector:
    app: pinterest-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
