apiVersion: v1
kind: Service
metadata:
  name: pinterest-service
spec:
  selector:
    app: pinterest-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Use a port of your choice for access
  type: NodePort
